#import "./DeploymentGroupInfo.gql"
#import "./ServiceInfo.gql"

query Instances($deploymentGroupPathName: String!){
  deploymentGroup(pathName: $deploymentGroupPathName) {
    ...DeploymentGroupInfo
    services {
      ...ServiceInfo
      parent
      connections
      currentMetrics {
        name
        value
        measurement
      }
      instances {
        uuid
      }
    }
  }
}
