#import "./DeploymentGroupInfo.gql"
#import "./ServiceInfo.gql"

query Services($deploymentGroupPathName: String!){
  deploymentGroup(pathName: $deploymentGroupPathName) {
    ...DeploymentGroupInfo
    services {
      ...ServiceInfo
    }
  }
}
