query Instances($deploymentGroupId: String!){
  deploymentGroup(id: $deploymentGroupId) {
    uuid
    id
    name
    services {
      uuid
      id
      name
      instances {
        uuid
        name
        metrics {
          type {
            id
          }
          data {
            timestamp
            value
          }
        }
      }
    }
  }
}
