// flow-typed signature: d02c352f523e296631d9b724125d25d2
// flow-typed version: <<STUB>>/zerorpc_v^0.9.7/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zerorpc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zerorpc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zerorpc/lib/buffer' {
  declare module.exports: any;
}

declare module 'zerorpc/lib/channel' {
  declare module.exports: any;
}

declare module 'zerorpc/lib/client' {
  declare module.exports: any;
}

declare module 'zerorpc/lib/events' {
  declare module.exports: any;
}

declare module 'zerorpc/lib/middleware' {
  declare module.exports: any;
}

declare module 'zerorpc/lib/server' {
  declare module.exports: any;
}

declare module 'zerorpc/lib/socket' {
  declare module.exports: any;
}

declare module 'zerorpc/lib/util' {
  declare module.exports: any;
}

declare module 'zerorpc/test/buffers' {
  declare module.exports: any;
}

declare module 'zerorpc/test/errors' {
  declare module.exports: any;
}

declare module 'zerorpc/test/heartbeats' {
  declare module.exports: any;
}

declare module 'zerorpc/test/invocation' {
  declare module.exports: any;
}

declare module 'zerorpc/test/lib/testutil' {
  declare module.exports: any;
}

declare module 'zerorpc/test/repro-10' {
  declare module.exports: any;
}

declare module 'zerorpc/test/streams' {
  declare module.exports: any;
}

declare module 'zerorpc/test/timeouts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zerorpc/index' {
  declare module.exports: $Exports<'zerorpc'>;
}
declare module 'zerorpc/index.js' {
  declare module.exports: $Exports<'zerorpc'>;
}
declare module 'zerorpc/lib/buffer.js' {
  declare module.exports: $Exports<'zerorpc/lib/buffer'>;
}
declare module 'zerorpc/lib/channel.js' {
  declare module.exports: $Exports<'zerorpc/lib/channel'>;
}
declare module 'zerorpc/lib/client.js' {
  declare module.exports: $Exports<'zerorpc/lib/client'>;
}
declare module 'zerorpc/lib/events.js' {
  declare module.exports: $Exports<'zerorpc/lib/events'>;
}
declare module 'zerorpc/lib/middleware.js' {
  declare module.exports: $Exports<'zerorpc/lib/middleware'>;
}
declare module 'zerorpc/lib/server.js' {
  declare module.exports: $Exports<'zerorpc/lib/server'>;
}
declare module 'zerorpc/lib/socket.js' {
  declare module.exports: $Exports<'zerorpc/lib/socket'>;
}
declare module 'zerorpc/lib/util.js' {
  declare module.exports: $Exports<'zerorpc/lib/util'>;
}
declare module 'zerorpc/test/buffers.js' {
  declare module.exports: $Exports<'zerorpc/test/buffers'>;
}
declare module 'zerorpc/test/errors.js' {
  declare module.exports: $Exports<'zerorpc/test/errors'>;
}
declare module 'zerorpc/test/heartbeats.js' {
  declare module.exports: $Exports<'zerorpc/test/heartbeats'>;
}
declare module 'zerorpc/test/invocation.js' {
  declare module.exports: $Exports<'zerorpc/test/invocation'>;
}
declare module 'zerorpc/test/lib/testutil.js' {
  declare module.exports: $Exports<'zerorpc/test/lib/testutil'>;
}
declare module 'zerorpc/test/repro-10.js' {
  declare module.exports: $Exports<'zerorpc/test/repro-10'>;
}
declare module 'zerorpc/test/streams.js' {
  declare module.exports: $Exports<'zerorpc/test/streams'>;
}
declare module 'zerorpc/test/timeouts.js' {
  declare module.exports: $Exports<'zerorpc/test/timeouts'>;
}
