export { default as CloseIcon } from './close';
export { default as DataCentersIcon } from './data-centers';
export { default as HealthyIcon } from './healthy';
export { default as HeartIcon } from './heart';
export { default as InputConfirmIcon } from './input-confirm';
export { default as InstancesMultipleIcon } from './instances-multiple';
export { default as NotificationIcon } from './notification';
export { default as SettingsIcon } from './settings';
export { default as UploadIcon } from './upload';
