module.exports = {
  Avatar: require('./components/avatar'),
  Base: require('./components/base'),
  Button: require('./components/button'),
  // ButtonIcon: require('./components/button-icon'),
  Checkbox: require('./components/checkbox'),
  Column: require('./components/column'),
  Container: require('./components/container'),
  Row: require('./components/row'),
  // Tab: require('./components/tabs/tab'),
  // Tabs: require('./components/tabs'),
  // Toggle: require('./components/toggle'),
  // Notificaton: require('./components/notification'),
  // Input: require('./components/input'),
  // Icon: require('./components/icon'),
  // RangeSlider: require('./components/range-slider'),
  // Radio: require('./components/radio'),
  // RadioGroup: require('./components/radio-group'),
  // Select: require('./components/select'),
  Widget: require('./components/widget'),
  // Pagination: require('./components/pagination'),
  // Modal: require('./components/modal')
};
