module.exports = {
  Avatar: require('./components/avatar'),
  Base: require('./components/base'),
  Button: require('./components/button'),
  Checkbox: require('./components/checkbox'),
  Column: require('./components/column'),
  Container: require('./components/container'),
  Input: require('./components/input'),
  Modal: require('./components/modal'),
  MiniMetric: require('./components/mini-metric'),
  Notificaton: require('./components/notification'),
  Pagination: require('./components/pagination'),
  Radio: require('./components/radio'),
  RadioGroup: require('./components/radio-group'),
  RangeSlider: require('./components/range-slider'),
  Row: require('./components/row'),
  Select: require('./components/select'),
  Tab: require('./components/tabs/tab'),
  Tabs: require('./components/tabs'),
  Toggle: require('./components/toggle'),
  Tooltip: require('./components/tooltip'),
  Widget: require('./components/widget'),
};
