NAME := $(lastword $(subst /, ,$(CURDIR)))

.PHONY: test
test:

.PHONY: test-ci
test-ci:

.PHONY: install
install: 

.PHONY: start
start:

.PHONY: install-production
install-production: 

.PHONY: build
build:
	docker build -t quay.io/yldio/joyent-portal-$(NAME) .

.PHONY: push
push:
	docker push quay.io/yldio/joyent-portal-$(NAME)

.PHONY: clean
clean:

.PHONY: lint
lint:

.PHONY: lint-ci
lint-ci:

.PHONY: licence-check
lint-ci:
