export const Forms = {
  SGC_F: 'SERVICE_GROUP_CREATE_FORM',
  SGC_T_F: 'SERVICE_GROUP_CREATE_TEMPLATE_FORM',
  SGC_F_F: 'SERVICE_GROUP_CREATE_FILTER_FORM',
  SGC_N_F: 'SERVICE_GROUP_CREATE_NAME_FORM',
  SGE_F: 'SERVICE_GROUP_EDIT_FORM',
  SGL_F_F: 'SERVICE_GROUP_LIST_FILTER_FORM',
  SGL_T_F: 'SERVICE_GROUP_LIST_TABLE_FORM'
};

export const Values = {
  SGC_N_V: 'SERVICE_GROUP_CREATE_NAME_VALUE',
  SGC_T_V: 'SERVICE_GROUP_CREATE_TEMPLATE_VALUE',
  SGE_N_V: 'SERVICE_GROUP_EDIT_NAME_VALUE',
  SGC_T_SB_V: 'SERVICE_GROUP_CREATE_TEMPLATE_SORT_BY_VALUE',
  SGC_T_SO_V: 'SERVICE_GROUP_CREATE_TEMPLATE_SORT_ORDER_VALUE',
  SGL_R_V: id => `SERVICE_GROUP_LIST_REMOVING_VALUE-${id}`,
  SGL_E_V: 'SERVICE_GROUP_LIST_ERROR_VALUE',
  SGL_SB_V: 'SERVICE_GROUP_LIST_SORT_BY_VALUE',
  SGL_SO_V: 'SERVICE_GROUP_LIST_SORT_ORDER_VALUE',
  SGS_R_V: id => `SERVICE_GROUP_SUMMARY_REMOVING_VALUE-${id}`,
  SGS_E_V: id => `SERVICE_GROUP_SUMMARY_ERROR_VALUE-${id}`
};
