query image($id: ID) {
  image(id: $id) {
    id
    name
    os
    version
    description
    type
    homepage
    published_at
    owner
    public
    state
    error {
      code
      message
    }
  }
}
